# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for building the project
FROM node:18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the source files to the container
COPY . .

# Build the TypeScript project
RUN npm run build

# Use a minimal Node.js runtime image for running the application
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy only the build output and node_modules from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Set environment variables
ENV VERODAT_AI_API_KEY=your-verodat-ai-api-key

# Expose any ports if necessary (this depends on how the MCP server operates, e.g., if it needs to listen on a network port)
# EXPOSE 3000

# Define the command to run the application
CMD ["node", "build/src/index.js"]
